[tool.poetry]
name = "django-tailwind"
version = "3.3.0"
description = "Tailwind CSS Framework for Django projects"
authors = ["Tim Kamanin <tim@timonweb.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/timonweb/django-tailwind"
keywords = ["django", "tailwind", "css"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Environment :: Web Environment",
    "Framework :: Django"
]
packages = [
    { include = "django_tailwind", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"
django = ">=2.2.28"
django-browser-reload = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-django = "^4.5.2"
tox = "^3.25.0"
pre-commit = "^2.19.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
black = "^22.3.0"
Sphinx = "^4.3.1"
recommonmark = "^0.7.1"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
